# Основы NumPy: Массивы и Векторные Вычисления

В этом ноутбуке мы рассмотрим основные концепции библиотеки NumPy: создание массивов, базовые операции и векторные вычисления.

In [5]:
import numpy as np

## 1. Создание массивов
NumPy предоставляет удобные способы для создания массивов различных типов и размеров.

In [6]:
a = np.array([1, 2, 3, 4])
print('Массив a:', a)

b = np.zeros((2,3))
print('Массив нулей b:\n', b)

c = np.ones((3,2))
print('Массив единиц c:\n', c)

d = np.arange(0, 10, 2)
print('Массив d с шагом 2:', d)

e = np.linspace(0, 1, 5)
print('Массив e с 5 значениями от 0 до 1:', e)

Массив a: [1 2 3 4]
Массив нулей b:
 [[0. 0. 0.]
 [0. 0. 0.]]
Массив единиц c:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Массив d с шагом 2: [0 2 4 6 8]
Массив e с 5 значениями от 0 до 1: [0.   0.25 0.5  0.75 1.  ]


## 2. Основные свойства массивов

In [10]:
print('Форма массива a:', a.shape)
print('Количество измерений массива b:', b.ndim)
print('Общее количество элементов массива a:', c.size)
print('Тип элементов массива a:', a.dtype)

Форма массива a: (4,)
Количество измерений массива b: 2
Общее количество элементов массива a: 6
Тип элементов массива a: int32


## 3. Индексация и срезы

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Массив arr:\n', arr)
print('Элемент [0,2]:', arr[2,2])
print('Первая строка:', arr[0,:])
print('Второй столбец:', arr[:,1])
print('Подмассив 2x2:', arr[0:2,1:3])

Массив arr:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [0,2]: 9
Первая строка: [1 2 3]
Второй столбец: [2 5 8]
Подмассив 2x2: [[2 3]
 [5 6]]


## 4. Арифметические операции

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print('Сложение:', x+y)
print('Вычитание:', x-y)
print('Умножение:', x*y)
print('Деление:', x/y)
print('Возведение в степень:', x**2)

Сложение: [5 7 9]
Вычитание: [-3 -3 -3]
Умножение: [ 4 10 18]
Деление: [0.25 0.4  0.5 ]
Возведение в степень: [1 4 9]


## 5. Линейная алгебра

In [7]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print('Умножение матриц:\n', C)
print('Транспонированная матрица A:\n', A.T)
det = np.linalg.det(A)
print('Определитель A:', det)

Умножение матриц:
 [[19 22]
 [43 50]]
Транспонированная матрица A:
 [[1 3]
 [2 4]]
Определитель A: -2.0000000000000004


## 6. Статистические функции

In [8]:
data = np.array([1,2,3,4,5])
print('Среднее:', np.mean(data))
print('Сумма:', np.sum(data))
print('Максимум:', np.max(data))
print('Минимум:', np.min(data))
print('Стандартное отклонение:', np.std(data))

Среднее: 3.0
Сумма: 15
Максимум: 5
Минимум: 1
Стандартное отклонение: 1.4142135623730951


## 7. Практическое задание
1. Создайте массив из 10 случайных чисел от 0 до 100.
2. Выведите среднее, максимум и минимум.
3. Создайте 3x3 матрицу и вычислите её определитель.
4. Выполните поэлементное умножение двух массивов длиной 5.